In [32]:
import numpy as np

In [33]:
arr1_1D = np.array([1,2,3,4,5]) # Create a 1D array, always pass a list, means separated by comma in np.array() and get vector
print("My 1d array is : ",arr1_1D)

arr2_2D = np.array([[1,2,3],[4,5,6]]) # Create a 2D array
print("My 2D array is : ",arr2_2D)

My 1d array is :  [1 2 3 4 5]
My 2D array is :  [[1 2 3]
 [4 5 6]]


In [34]:
# Now creating those array, we can easily perfrom vector operations

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

arr1 = np.array(list1)
arr2 = np.array(list2)

# Vector addition
# list cannot do this, it will join the two lists
list_sum = list1 + list2
print("Sum of two lists is : ", list_sum)
# but numpy arrays can do this, it will add the two arrays element-wise
arr_sum = arr1 + arr2
print("Sum of two arrays is : ", arr_sum)

# Vector subtraction
# list_sub = list1 - list2  # This will give an error, lists cannot be
# but numpy arrays can do this, it will subtract the two arrays element-wise
arr_sub = arr1 - arr2
print("Subtraction of two arrays is : ", arr_sub)

# Vector multiplication
# list_mul = list1 * list2  # This will give an error, lists cannot be
# but numpy arrays can do this, it will multiply the two arrays element-wise
arr_mul = arr1 * arr2
print("Multiplication of two arrays is : ", arr_mul)

# Vector division
# list_div = list1 / list2  # This will give an error, lists cannot
# but numpy arrays can do this, it will divide the two arrays element-wise
arr_div = arr1 / arr2
print("Division of two arrays is : ", arr_div)

list_tuice = list1 * 2  # This will give a list with each element multiplied by 2
print("List with each element multiplied by 2 is : ", list_tuice)
arr_tuice = arr1 * 2  # This will give an array with each element multiplied by 2
print("Array with each element multiplied by 2 is : ", arr_tuice)



Sum of two lists is :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Sum of two arrays is :  [ 7  9 11 13 15]
Subtraction of two arrays is :  [-5 -5 -5 -5 -5]
Multiplication of two arrays is :  [ 6 14 24 36 50]
Division of two arrays is :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
List with each element multiplied by 2 is :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array with each element multiplied by 2 is :  [ 2  4  6  8 10]


In [35]:
arr3 = np.arange(10) # Create an array with 10 elements from 0 to 9
print("Array with 100 elements from 0 to 9 is : ", arr3)

arr4 = np.arange(10, 20) # Create an array with 10 elements from 10 to 19
print("Array with 10 elements from 10 to 19 is : ", arr4)

arr5 = np.arange(10, 20, 2) # Create an array from 10 to 19 with step size of 2
print("Array with 10 elements from 10 to 19 with step size of 2 is : ", arr5)

arr6_zero = np.zeros((2, 3)) # Create a 2D array with 2 rows and 3 columns filled with zeros
print("2D array with 2 rows and 3 columns filled with zeros is : \n", arr6_zero)

arr7_ones = np.ones((2,3)) # Create a 2D array with 2 rows and 3 columns filled with ones
print("2D array with 2 rows and 3 columns filled with ones is : \n", arr7_ones)

arr8_of_one_partical_value = np.full((2,3),5) # Create a 2D array with 2 rows and 3 columns filled with 5, formate is np.full((rows, columns), value)
print("2D array with 2 rows and 3 columns filled with 5 is : \n", arr8_of_one_partical_value)

arr9_random_values = np.random.random((2,3)) # Create a 2D array with 2 rows and 3 columns filled with random values between 0 and 1
print("2D array with 2 rows and 3 columns filled with random values between 0 and 1 is : \n", arr9_random_values)

Array with 100 elements from 0 to 9 is :  [0 1 2 3 4 5 6 7 8 9]
Array with 10 elements from 10 to 19 is :  [10 11 12 13 14 15 16 17 18 19]
Array with 10 elements from 10 to 19 with step size of 2 is :  [10 12 14 16 18]
2D array with 2 rows and 3 columns filled with zeros is : 
 [[0. 0. 0.]
 [0. 0. 0.]]
2D array with 2 rows and 3 columns filled with ones is : 
 [[1. 1. 1.]
 [1. 1. 1.]]
2D array with 2 rows and 3 columns filled with 5 is : 
 [[5 5 5]
 [5 5 5]]
2D array with 2 rows and 3 columns filled with random values between 0 and 1 is : 
 [[0.9147556  0.49986842 0.77619238]
 [0.7759805  0.95967583 0.20431217]]


In [36]:
vector = np.array([1,2,3,4,5])  # Create a vector (1D array)
print("My vector is : ", vector)

matrix = np.array([[1,2,3],[4,5,6]]) # Create a 2D array (matrix)
print("My matrix is : \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]]) # Create a 3D array (tensor)
print("My tensor is : \n", tensor)

My vector is :  [1 2 3 4 5]
My matrix is : 
 [[1 2 3]
 [4 5 6]]
My tensor is : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
# Array properties
arr10 = np.array([[1,2,3],[4,5,6]])  # Create a 2D array for properties demonstration

print("Array is : \n", arr10) 
print("Shape of the array is : ", arr10.shape)  # Shape of the array
print("Number of dimensions of the array is : ", arr10.ndim)   # Number of dimensions of the array
print("Data type of the array is : ", arr10.dtype)  # Data type of the array
print("Size of the array is : ", arr10.size)  # Size of the array
print("Item size of the array is : ", arr10.itemsize)  # itemsize gives the number of bytes used to store one element in the array.
print("Total bytes of the array is : ", arr10.nbytes)  # Total bytes
print("The transepose of the array is : \n", arr10.T)  # Transpose of the array

Array is : 
 [[1 2 3]
 [4 5 6]]
Shape of the array is :  (2, 3)
Number of dimensions of the array is :  2
Data type of the array is :  int64
Size of the array is :  6
Item size of the array is :  8
Total bytes of the array is :  48
The transepose of the array is : 
 [[1 4]
 [2 5]
 [3 6]]


In [38]:
# list3 = [1,2,3,4,5,6,7,8,9,10,11,12]
arr11 = np.arange(12) # Create a 1D array with 12 elements from 0 to 11
print("1D array with 12 elements from 0 to 11 is : ", arr11)

reshape_arr11_of2D = arr11.reshape(3,4) # Reshape the array to 3 rows and 4 columns
print("Reshaped array to 3 rows and 4 columns is : \n", reshape_arr11_of2D)

flattened_arr11 = reshape_arr11_of2D.flatten() # Flatten the array to 1D
print("Flattened array is : ", flattened_arr11)

reshape_arr12_of3D = np.arange(24).reshape(2,3,4) # Reshape the array to 2 depth, 3 row and 4 columns
print("Reshaped array to 2 rows, 2 columns and 3 depth is : \n", reshape_arr12_of3D)
'''
    c0 c1 c2 c3
[[[ 0  1  2  3]     row0    |
  [ 4  5  6  7]     row1    |-> depth0
  [ 8  9 10 11]]    row2    |

 [[12 13 14 15]     row0    |
  [16 17 18 19]     row1    |-> depth1
  [20 21 22 23]]]   row2    |
'''
# The access process is arr[depth][row][column]
print("Accessing the element at depth 0, row 1, column 2 is : ", reshape_arr12_of3D[0][1][2]) # Accessing the element at depth 0, row 1, column 2

ravel_arr12 = reshape_arr12_of3D.ravel() # Ravel the array to 1D
print("Raveled array is : ", ravel_arr12)


1D array with 12 elements from 0 to 11 is :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array to 3 rows and 4 columns is : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array to 2 rows, 2 columns and 3 depth is : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Accessing the element at depth 0, row 1, column 2 is :  6
Raveled array is :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [39]:
# flatten() -> Always returns a copy
# ravel() -> Returns a view (if possible)

arr13 = np.array([[1, 2], [3, 4]])

flat = arr13.flatten()
rav = arr13.ravel()

flat[0] = 100   # This will not affect the original array
rav[1] = 200    # This will affect the original array if it is a view

print("Original array:\n", arr13)
print("Flattened copy:\n", flat)
print("Raveled view:\n", rav)

Original array:
 [[  1 200]
 [  3   4]]
Flattened copy:
 [100   2   3   4]
Raveled view:
 [  1 200   3   4]


In [40]:
# array slicing
# array slicing is same as list slicing, but with some additional features, now list is 1D, so we don't show the 1D array slicing
# but in numpy array, we can slice 2D and 3D arrays as well
arr14 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("Original array:\n", arr14)
# The formate is arr[row_start:row_end, column_start:column_end], if we don't specify the start or end, it will take the whole row or column by default, the end part always excludes the end index
sliced_arr14 = arr14[:2, :3]    # Slicing the array to get the first two rows and first three columns
print("Sliced array (first two rows and first three columns):\n", sliced_arr14)
# Slicing the array to get the second row and all columns
sliced_row = arr14[1, :]  # This means row 1 and all columns
print("Sliced row (second row and all columns):\n", sliced_row)
# Slicing the array to get the last two rows and last two columns
sliced_arr14_last = arr14[-2:, -2:]  # Slicing the array to get the last two rows and last two columns
print("Sliced array (last two rows and last two columns):\n", sliced_arr14_last)

# The formate of 3D array slicing is arr[depth_start:depth_end, row_start:row_end, column_start:column_end]

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced array (first two rows and first three columns):
 [[1 2 3]
 [5 6 7]]
Sliced row (second row and all columns):
 [5 6 7 8]
Sliced array (last two rows and last two columns):
 [[ 7  8]
 [11 12]]


In [41]:
# Sorting the array
    # For 1D array
arr15 = np.array([3, 1, 4, 2, 5])
sorted_arr15 = np.sort(arr15)  # Sort the array in ascending order
print("Sorted array in ascending order:", sorted_arr15,"\n\n\n")

    # For 2D array
arr16 = np.array([[3, 1, 7], 
                  [2, 5, 6]])
# If we don't specify the axis,then it is axis = -1 and it will sort the array in ascending order, flattened
sorted_arr16 = np.sort(arr16)  # Sort the array in ascending order, flattened
print("Sorted array in ascending order (flattened):\n", sorted_arr16)
sorted_arr16_col = np.sort(arr16, axis=0)  # Sort the array along the first axis (columns)
print("Sorted array along the first axis (columns):\n", sorted_arr16_col)
sorted_arr16_row = np.sort(arr16, axis=1)  # Sort the array along the second axis (rows)
print("Sorted array along the second axis (rows):\n", sorted_arr16_row)

Sorted array in ascending order: [1 2 3 4 5] 



Sorted array in ascending order (flattened):
 [[1 3 7]
 [2 5 6]]
Sorted array along the first axis (columns):
 [[2 1 6]
 [3 5 7]]
Sorted array along the second axis (rows):
 [[1 3 7]
 [2 5 6]]


In [42]:
# Filter, means to get the elements that satisfy a condition
arr17 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_num = arr17[arr17 % 2 == 0]    # formate is new_array = old_array[condition], where condition is a boolean array
print("Even numbers in the array are: ", even_num)

# Filter with mask
mask = arr17 > 5  # Create a mask for elements greater than 5
filtered_arr17 = arr17[mask]  # Use the mask to filter the array
print("Filtered array with elements greater than 5: ", filtered_arr17)

# Fancy indexing
arr18 = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
# Fancy indexing allows us to access multiple elements at once using a list or array of indices
row_indices = [0, 2]  # Indices of the rows we want to access
col_indices = [1, 2]  # Indices of the columns we want to
fancy_indexed_arr18 = arr18[row_indices, col_indices]  # Accessing
print("Fancy indexed array (accessing elements at row indices 0 and 2, and column indices 1 and 2): ", fancy_indexed_arr18)

Even numbers in the array are:  [ 2  4  6  8 10]
Filtered array with elements greater than 5:  [ 6  7  8  9 10]
Fancy indexed array (accessing elements at row indices 0 and 2, and column indices 1 and 2):  [2 9]


In [43]:
# where() function, the where() function returns the indices of elements that satisfy a condition
arr18 = np.arange(10)
indices = np.where(arr18 > 5)  # fromate is np.where(condition), where condition is an array
print("Indices of elements greater than 5 in the array: ", indices)
print("Elements greater than 5 in the array: ", arr18[indices])  # Accessing the elements using the indices

conditional_arr18 = np.where(arr18 > 5, arr18 * 3, -1)  # fromate is np.where(condition, value_if_true, value_if_false)
'''
it means -> 
if(arr18 > 5) then arr18
else -1
'''
print("Conditional array : ", conditional_arr18)

Indices of elements greater than 5 in the array:  (array([6, 7, 8, 9]),)
Elements greater than 5 in the array:  [6 7 8 9]
Conditional array :  [-1 -1 -1 -1 -1 -1 18 21 24 27]


In [44]:
# adding array, combined array, array compatibility and delete
arr19 = np.array([1,2,3])
arr20 = np.array([4,5,6])
arr_adding = arr19 + arr20  # This will add the two arrays element-wise
print("Added array (element-wise addition): ", arr_adding)
combined_arr18 = np.concatenate((arr19, arr20))  # This will combine the two arrays
print("Combined array: ", combined_arr18)
print("Compatibility shape : ", arr19.shape == arr20.shape)
# delete an item from the array
delete_arr19 = np.delete(arr19, 1)  # Delete the element at index 1, Note that this does not modify the original array, it returns a new array.When we delete an element, it return the item, but here it gives a new array
print("Array after deleting the element at index 1: ", delete_arr19)


Added array (element-wise addition):  [5 7 9]
Combined array:  [1 2 3 4 5 6]
Compatibility shape :  True
Array after deleting the element at index 1:  [1 3]


In [45]:
# add item as row or column, row means vertical and column means horizontal
arr21 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
# add item as row
new_row = np.array([7, 8, 9])  # New row to be added
arr21_row_added = np.vstack((arr21, new_row))  # Use vstack to add the new row
print("Array after adding new row:\n", arr21_row_added)
# add item as column
new_col = np.array([[10], [11], [12]])  # New column to be added
arr21_col_added = np.hstack((arr21_row_added, new_col))  # Use hstack to add the new column
arr21_col_added2 = np.hstack((arr21_col_added, [[13], [14],[ 15]]))  # Adding a new column with different values
print("Array after adding new column:\n", arr21_col_added2)

Array after adding new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding new column:
 [[ 1  2  3 10 13]
 [ 4  5  6 11 14]
 [ 7  8  9 12 15]]
