In [2]:
import numpy as np

In [ ]:
arr1_1D = np.array([1,2,3,4,5]) # Create a 1D array, always pass a list, means separated by comma in np.array() and get vector
print("My 1d array is : ",arr1_1D)

arr2_2D = np.array([[1,2,3],[4,5,6]]) # Create a 2D array
print("My 2D array is : ",arr2_2D)

My 1d array is :  [1 2 3 4 5]
My 2D array is :  [[1 2 3]
 [4 5 6]]


In [ ]:
# Now creating those array, we can easily perfrom vector operations

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

arr1 = np.array(list1)
arr2 = np.array(list2)

# Vector addition
# list cannot do this, it will join the two lists
list_sum = list1 + list2
print("Sum of two lists is : ", list_sum)
# but numpy arrays can do this, it will add the two arrays element-wise
arr_sum = arr1 + arr2
print("Sum of two arrays is : ", arr_sum)

# Vector subtraction
# list_sub = list1 - list2  # This will give an error, lists cannot be
# but numpy arrays can do this, it will subtract the two arrays element-wise
arr_sub = arr1 - arr2
print("Subtraction of two arrays is : ", arr_sub)

# Vector multiplication
# list_mul = list1 * list2  # This will give an error, lists cannot be
# but numpy arrays can do this, it will multiply the two arrays element-wise
arr_mul = arr1 * arr2
print("Multiplication of two arrays is : ", arr_mul)

# Vector division
# list_div = list1 / list2  # This will give an error, lists cannot
# but numpy arrays can do this, it will divide the two arrays element-wise
arr_div = arr1 / arr2
print("Division of two arrays is : ", arr_div)

list_tuice = list1 * 2  # This will give a list with each element multiplied by 2
print("List with each element multiplied by 2 is : ", list_tuice)
arr_tuice = arr1 * 2  # This will give an array with each element multiplied by 2
print("Array with each element multiplied by 2 is : ", arr_tuice)



Sum of two lists is :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Sum of two arrays is :  [ 7  9 11 13 15]
Subtraction of two arrays is :  [-5 -5 -5 -5 -5]
Multiplication of two arrays is :  [ 6 14 24 36 50]
Division of two arrays is :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
List with each element multiplied by 2 is :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array with each element multiplied by 2 is :  [ 2  4  6  8 10]


In [22]:
arr3 = np.arange(10) # Create an array with 10 elements from 0 to 9
print("Array with 100 elements from 0 to 9 is : ", arr3)

arr4 = np.arange(10, 20) # Create an array with 10 elements from 10 to 19
print("Array with 10 elements from 10 to 19 is : ", arr4)

arr5 = np.arange(10, 20, 2) # Create an array from 10 to 19 with step size of 2
print("Array with 10 elements from 10 to 19 with step size of 2 is : ", arr5)

arr6_zero = np.zeros((2, 3)) # Create a 2D array with 2 rows and 3 columns filled with zeros
print("2D array with 2 rows and 3 columns filled with zeros is : \n", arr6_zero)

arr7_ones = np.ones((2,3)) # Create a 2D array with 2 rows and 3 columns filled with ones
print("2D array with 2 rows and 3 columns filled with ones is : \n", arr7_ones)

arr8_of_one_partical_value = np.full((2,3),5) # Create a 2D array with 2 rows and 3 columns filled with 5, formate is np.full((rows, columns), value)
print("2D array with 2 rows and 3 columns filled with 5 is : \n", arr8_of_one_partical_value)

arr8_random_values = np.random.random((2,3)) # Create a 2D array with 2 rows and 3 columns filled with random values between 0 and 1
print("2D array with 2 rows and 3 columns filled with random values between 0 and 1 is : \n", arr8_random_values)




Array with 100 elements from 0 to 9 is :  [0 1 2 3 4 5 6 7 8 9]
Array with 10 elements from 10 to 19 is :  [10 11 12 13 14 15 16 17 18 19]
Array with 10 elements from 10 to 19 with step size of 2 is :  [10 12 14 16 18]
2D array with 2 rows and 3 columns filled with zeros is : 
 [[0. 0. 0.]
 [0. 0. 0.]]
2D array with 2 rows and 3 columns filled with ones is : 
 [[1. 1. 1.]
 [1. 1. 1.]]
2D array with 2 rows and 3 columns filled with 5 is : 
 [[5 5 5]
 [5 5 5]]
2D array with 2 rows and 3 columns filled with random values between 0 and 1 is : 
 [[0.52470643 0.5573796  0.22595808]
 [0.82354599 0.85920373 0.43076294]]
